// File generated by FlutterFire CLI.
// Contains Firebase configuration options for your app.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Configuration options for Firebase services.
/// This class provides platform-specific Firebase options.
class DefaultFirebaseOptions {
  /// Default Firebase options for the current platform.
  static FirebaseOptions get currentPlatform => _getOptions();

  /// Get platform-specific Firebase options.
  static FirebaseOptions _getOptions() {
    if (kIsWeb) {
      return web;
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError('Windows is not supported by Firebase.');
      case TargetPlatform.linux:
        throw UnsupportedError('Linux is not supported by Firebase.');
      default:
        throw UnsupportedError('Unknown platform: $defaultTargetPlatform');
    }
  }

  /// Web-specific Firebase options.
  static final FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfaX4V-FvnvyYJTBuI3PBVgIOy83O7Ehc',
    authDomain: 'abdifahadi-raabta.firebaseapp.com',
    projectId: 'abdifahadi-raabta',
    storageBucket: 'abdifahadi-raabta.firebasestorage.app',
    messagingSenderId: '507820378047',
    appId: '1:507820378047:web:a78393966656f46391c30a',
    measurementId: 'G-W8DF9B0CB8',
  );

  /// Android-specific Firebase options.
  static final FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfaX4V-FvnvyYJTBuI3PBVgIOy83O7Ehc',
    appId: '1:507820378047:android:a78393966656f46391c30a',
    messagingSenderId: '507820378047',
    projectId: 'abdifahadi-raabta',
    storageBucket: 'abdifahadi-raabta.firebasestorage.app',
  );

  /// iOS-specific Firebase options.
  static final FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfaX4V-FvnvyYJTBuI3PBVgIOy83O7Ehc',
    appId: '1:507820378047:ios:a78393966656f46391c30a',
    messagingSenderId: '507820378047',
    projectId: 'abdifahadi-raabta',
    storageBucket: 'abdifahadi-raabta.firebasestorage.app',
    iosBundleId: 'com.abdifahadi.raabta',
  );

  /// macOS-specific Firebase options.
  static final FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfaX4V-FvnvyYJTBuI3PBVgIOy83O7Ehc',
    appId: '1:507820378047:ios:a78393966656f46391c30a',
    messagingSenderId: '507820378047',
    projectId: 'abdifahadi-raabta',
    storageBucket: 'abdifahadi-raabta.firebasestorage.app',
    iosBundleId: 'com.abdifahadi.raabta',
  );
}
